"""EVGAMES end-to-end checks in Chromium. Usage: python3 tools/e2e_platform.py <base_url> <screenshot_dir>"""
import json, sys, time
from playwright.sync_api import sync_playwright
base, out = sys.argv[1].rstrip('/'), sys.argv[2]
errors, results = [], []
def check(name, ok, extra=''):
    results.append((name, bool(ok))); print(('PASS ' if ok else 'FAIL ') + name + (f' — {extra}' if extra else ''))

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={'width': 1440, 'height': 900})
    page = ctx.new_page()
    page.on('pageerror', lambda e: errors.append(f'pageerror: {e}'))
    page.on('console', lambda m: errors.append(f'console.{m.type}: {m.text}') if m.type == 'error' else None)
    page.goto(base + '/'); page.wait_for_selector('.wordmark'); time.sleep(0.8)
    page.screenshot(path=f'{out}/01-home.png')
    page.screenshot(path=f'{out}/01-home-full.png', full_page=True)
    check('home title', page.title() == 'EVGAMES — Browser Games', page.title())
    check('hero has Graj teraz', page.get_by_role('link', name='Graj teraz', exact=True).count() == 1)
    check('library shows both games', page.locator('#biblioteka .card:not(.soon)').count() == 2)
    # home search filter (local)
    page.fill('#lib-title-q', 'xyz123'); time.sleep(0.2)
    check('no-results state', page.locator('#biblioteka .empty').count() == 1)
    page.locator('#biblioteka .empty button').click(); time.sleep(0.2)
    check('clear filters restores', page.locator('#biblioteka .card:not(.soon)').count() == 2)
    page.fill('#lib-title-q', 'swietle'); time.sleep(0.2)
    check('diacritic-insensitive search finds Lampiarz', page.locator('#biblioteka .card:not(.soon)').count() == 1)
    page.fill('#lib-title-q', '')
    check('empty categories disabled', page.get_by_role('button', name='Puzzle wkrótce').is_disabled())
    page.get_by_role('button', name='Akcja 1').click(); time.sleep(0.2)
    check('category filter Akcja shows Popielny Dzwon', page.locator('#biblioteka .card:not(.soon)').count() == 1 and 'Popielny Dzwon' in (page.locator('#biblioteka .card:not(.soon)').first.text_content() or ''))
    page.get_by_role('button', name='Strategia 1').click(); time.sleep(0.2)
    check('category filter Strategia', page.locator('#biblioteka .card:not(.soon)').count() == 1)
    page.get_by_role('button', name='Wszystkie 2').click()
    # favourite toggle
    page.locator('#biblioteka .card:has-text("Lampiarz") .fav-btn').first.click(); time.sleep(0.3)
    favs = page.evaluate("localStorage.getItem('evgames.favorites.v1')")
    check('favorite stored', favs == '["lampiarz"]', favs)
    check('nav badge shows 1', page.locator('.nav .badge').inner_text() == '1')
    # header search -> /games?q=
    page.fill('#search-desktop', 'roguelite'); page.keyboard.press('Enter'); time.sleep(0.5)
    check('header search navigates', '/games?q=roguelite' in page.url, page.url)
    check('library result for roguelite', page.locator('.card:not(.soon)').count() == 2)
    page.screenshot(path=f'{out}/02-library.png')
    page.goto(base + '/games?q=zzzz'); time.sleep(0.6)
    check('direct load /games?q= shows empty state', page.locator('.empty').count() == 1)
    page.screenshot(path=f'{out}/03-empty.png')
    # details
    page.goto(base + '/games/lampiarz'); page.wait_for_selector('.detail-hero h1'); time.sleep(0.6)
    check('detail page refresh-safe + title', page.title() == 'Lampiarz — EVGAMES', page.title())
    page.screenshot(path=f'{out}/04-detail.png')
    page.screenshot(path=f'{out}/04-detail-full.png', full_page=True)
    page.locator('.shots button').first.click(); time.sleep(0.3)
    check('lightbox opens', page.locator('.lightbox').count() == 1)
    page.keyboard.press('Escape'); time.sleep(0.2)
    check('lightbox closes on Esc', page.locator('.lightbox').count() == 0)
    # play
    page.get_by_role('link', name='Zagraj teraz').first.click()
    page.wait_for_selector('.player iframe')
    t0 = time.time()
    while page.locator('.player .state').count() and time.time() - t0 < 15: time.sleep(0.2)
    check('game started in player', page.locator('.player .state').count() == 0, f'{time.time()-t0:.1f}s')
    check('play url', page.url.endswith('/play/lampiarz'), page.url)
    frame = page.frame_locator('.player iframe')
    time.sleep(1.5)
    page.screenshot(path=f'{out}/05-player-menu.png')
    rec = page.evaluate("JSON.parse(localStorage.getItem('evgames.recent.v1'))")
    check('recently played stored', rec and rec[0]['slug'] == 'lampiarz')
    frame.get_by_role('button', name='Nowa noc').click(); time.sleep(0.4)
    frame.get_by_role('button', name='Zapal pierwszą latarnię').click(); time.sleep(0.8)
    frame.get_by_role('button', name='Do roboty').click(); time.sleep(0.3)
    for k in ['ArrowRight', 'ArrowRight', 'ArrowDown', 'Space', 'ArrowUp', 'ArrowLeft']:
        page.keyboard.press(k); time.sleep(0.15)
    time.sleep(0.6)
    run = page.evaluate("JSON.parse(localStorage.getItem('lampiarz.run.v1'))")
    check('keyboard reaches game + save written (same origin)', run and run['district']['turn'] >= 3, f"turn={run and run['district']['turn']}")
    page.screenshot(path=f'{out}/06-player-game.png')
    # refresh directly on /play/lampiarz keeps progress
    page.reload(); page.wait_for_selector('.player iframe')
    t0 = time.time()
    while page.locator('.player .state').count() and time.time() - t0 < 15: time.sleep(0.2)
    check('refresh on /play works', page.locator('.player .state').count() == 0)
    time.sleep(1)
    check('game offers continue after refresh', frame.get_by_role('button', name='Kontynuuj noc').count() == 1)
    # back navigation
    page.go_back(); time.sleep(0.6)
    check('browser back leaves player', '/play/' not in page.url, page.url)
    page.go_forward(); time.sleep(0.6)
    check('browser forward returns to player', page.url.endswith('/play/lampiarz'))
    page.get_by_role('link', name='Wróć do strony gry').click(); time.sleep(0.5)
    check('player back button -> detail', page.url.endswith('/games/lampiarz'))
    # favourites page
    page.goto(base + '/favorites'); time.sleep(0.6)
    check('favorites page lists game + recent', page.locator('.card').count() == 1 and page.locator('.mini').count() == 1)
    page.screenshot(path=f'{out}/07-favorites.png')
    page.locator('.card .fav-btn').click(); time.sleep(0.3)
    check('remove favorite -> empty state', page.locator('#fav-title').count() == 1 and page.locator('.empty').count() >= 1)
    page.get_by_role('button', name='Wyczyść historię').click(); time.sleep(0.2)
    check('clear history -> empty state', page.locator('.mini').count() == 0)
    # other pages
    for path, sel in [('/discover', '.cat-grid'), ('/new', '.featured'), ('/privacy', '.legal'), ('/nie-ma-takiej', '.notfound'), ('/games/nieistnieje', '.notfound'), ('/play/nieistnieje', '.notfound')]:
        page.goto(base + path); time.sleep(0.5)
        check(f'route {path}', page.locator(sel).count() >= 1)
    page.goto(base + '/discover'); time.sleep(0.4); page.screenshot(path=f'{out}/08-discover.png')
    page.goto(base + '/nie-ma-takiej'); time.sleep(0.4); page.screenshot(path=f'{out}/09-404.png')
    # missing game build -> error state
    page.route('**/g/lampiarz/index.html', lambda r: r.fulfill(status=404, body='<!doctype html><title>404: NOT_FOUND</title><h1>This page could not be found</h1>', content_type='text/html'))
    page.goto(base + '/play/lampiarz'); page.wait_for_selector('.player .state[role=alert]', timeout=18000)
    check('missing game build -> error state', page.locator('.player .state[role=alert]').count() == 1)
    page.screenshot(path=f'{out}/10-player-error.png')
    page.unroute('**/g/lampiarz/index.html')
    # ---- second title: Popielny Dzwon
    page.goto(base + '/games/popielny-dzwon'); page.wait_for_selector('.detail-hero h1'); time.sleep(0.6)
    check('Popielny Dzwon detail page', page.title() == 'Popielny Dzwon — EVGAMES', page.title())
    check('Popielny Dzwon shows keyboard/pad requirement', page.get_by_text('Wymaga klawiatury i myszy albo pada').count() == 1)
    page.screenshot(path=f'{out}/11-pd-detail.png')
    lamp_before = page.evaluate("localStorage.getItem('lampiarz.profile.v1')")
    page.goto(base + '/play/popielny-dzwon'); page.wait_for_selector('.player iframe')
    t0 = time.time()
    while page.locator('.player .state').count() and time.time() - t0 < 15: time.sleep(0.2)
    check('Popielny Dzwon started in player', page.locator('.player .state').count() == 0, f'{time.time()-t0:.1f}s')
    pf = page.frame_locator('.player iframe')
    pf.locator('.pd-logo').wait_for(timeout=10000)
    check('Popielny Dzwon title screen inside iframe', pf.locator('canvas.pd-canvas').count() == 1 and pf.get_by_role('button', name='Nowa gra').count() == 1)
    pf.get_by_role('button', name='Nowa gra').click(); time.sleep(0.4)
    pf.get_by_role('button', name='Obudź się').click(); time.sleep(2.0)
    page.screenshot(path=f'{out}/12-pd-player.png')
    pd_save = page.evaluate("localStorage.getItem('popielnydzwon.save.v1')")
    check('Popielny Dzwon saves under its own key', bool(pd_save) and '"version":1' in pd_save)
    check('Lampiarz save untouched by Popielny Dzwon', page.evaluate("localStorage.getItem('lampiarz.profile.v1')") == lamp_before)
    keys = page.evaluate("Object.keys(localStorage)")
    check('no unexpected storage keys', all(k.startswith(('evgames.', 'lampiarz.', 'popielnydzwon.')) for k in keys), ','.join(keys))
    # keyboard focus visible on nav
    page.goto(base + '/'); time.sleep(0.4)
    page.keyboard.press('Tab'); page.keyboard.press('Tab')
    check('keyboard tab reaches header', page.evaluate("document.activeElement && document.activeElement.closest('header') !== null"))
    ctx.close()

    m = b.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, has_touch=True, is_mobile=True)
    mp = m.new_page(); mp.on('pageerror', lambda e: errors.append(f'pageerror(m): {e}'))
    mp.goto(base + '/'); mp.wait_for_selector('.wordmark'); time.sleep(0.6)
    mp.screenshot(path=f'{out}/m1-home.png')
    sw = mp.evaluate('document.documentElement.scrollWidth')
    check('mobile no horizontal scroll', sw <= 390, f'scrollWidth={sw}')
    mp.get_by_role('button', name='Otwórz menu').tap(); time.sleep(0.4)
    mp.screenshot(path=f'{out}/m2-menu.png')
    mp.locator('#mobile-nav a.m', has_text='Gry').tap(); time.sleep(0.5)
    check('mobile menu navigates', mp.url.endswith('/games'))
    mp.screenshot(path=f'{out}/m3-library.png', full_page=True)
    mp.goto(base + '/games/lampiarz'); time.sleep(0.6)
    sw = mp.evaluate('document.documentElement.scrollWidth')
    check('mobile detail no h-scroll', sw <= 390, f'scrollWidth={sw}')
    mp.screenshot(path=f'{out}/m4-detail.png', full_page=True)
    mp.goto(base + '/play/popielny-dzwon'); time.sleep(2)
    coarse = mp.evaluate("matchMedia('(hover: none) and (pointer: coarse)').matches")
    n_note = mp.locator('.player [role=note]').count()
    # the note must appear exactly when the browser reports a touch-only device
    check('Popielny Dzwon touch notice matches the device', n_note == (1 if coarse else 0), f'coarse={coarse} notes={n_note}')
    mp.screenshot(path=f'{out}/m6-pd-player.png')
    mp.goto(base + '/play/lampiarz'); time.sleep(3)
    check('mobile player starts', mp.locator('.player .state').count() == 0)
    mp.screenshot(path=f'{out}/m5-player.png')
    m.close(); b.close()

print(f"\n{sum(ok for _, ok in results)}/{len(results)} checks passed")
print('ERRORS:', json.dumps(errors, ensure_ascii=False, indent=1) if errors else 'none')
